import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/menu_item_model.dart';

class DummyDataService {
  final CollectionReference _menuCollection =
      FirebaseFirestore.instance.collection('menu_items');

  Future<void> generateDummyData() async {
    // Danh sách 20 món ăn mẫu
    List<MenuItemModel> dummyItems = [
      // --- APPETIZERS (Khai vị) ---
      MenuItemModel(
        itemId: '',
        name: 'Gỏi Cuốn Tôm Thịt',
        description: 'Gỏi cuốn tươi ngon với tôm, thịt heo, bún và rau sống.',
        category: 'Appetizer',
        price: 35000,
        imageUrl: 'https://cdn.tgdd.vn/2021/01/CookProduct/1260-1200x676-2.jpg',
        ingredients: ['Tôm', 'Thịt heo', 'Bún', 'Bánh tráng', 'Rau sống'],
        isVegetarian: false,
        isSpicy: false,
        preparationTime: 10,
        rating: 4.8,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Chả Giò Rế',
        description: 'Chả giò chiên giòn rụm với nhân thịt và khoai môn.',
        category: 'Appetizer',
        price: 45000,
        imageUrl: 'https://bizweb.dktcdn.net/thumb/1024x1024/100/356/800/products/cha-gio-re-thit-ngon-ngon-goi-500g-30-cuon-202203111453303723.jpg',
        ingredients: ['Thịt heo', 'Khoai môn', 'Bánh tráng rế', 'Mộc nhĩ'],
        isVegetarian: false,
        isSpicy: false,
        preparationTime: 15,
        rating: 4.5,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Salad Rau Củ',
        description: 'Salad tươi mát với sốt mè rang.',
        category: 'Appetizer',
        price: 30000,
        imageUrl: 'https://cdn.tgdd.vn/2020/08/CookProduct/1200-1200x676-80.jpg',
        ingredients: ['Xà lách', 'Cà chua', 'Dưa leo', 'Sốt mè rang'],
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 10,
        rating: 4.2,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Súp Bí Đỏ',
        description: 'Súp kem bí đỏ béo ngậy, dùng kèm bánh mì nướng.',
        category: 'Appetizer',
        price: 40000,
        imageUrl: 'https://cdn.tgdd.vn/2020/09/CookProduct/1200-1200x676-23.jpg',
        ingredients: ['Bí đỏ', 'Kem tươi', 'Hành tây'],
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 20,
        rating: 4.6,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Cánh Gà Chiên Nước Mắm',
        description: 'Cánh gà chiên giòn tẩm sốt nước mắm đậm đà.',
        category: 'Appetizer',
        price: 60000,
        imageUrl: 'https://cdn.tgdd.vn/2020/07/CookProduct/1200-1200x676-53.jpg',
        ingredients: ['Cánh gà', 'Nước mắm', 'Tỏi', 'Ớt'],
        isVegetarian: false,
        isSpicy: true,
        preparationTime: 25,
        rating: 4.9,
        createdAt: DateTime.now(),
      ),

      // --- MAIN COURSE (Món chính) ---
      MenuItemModel(
        itemId: '',
        name: 'Phở Bò Đặc Biệt',
        description: 'Phở bò tái nạm gầu gân, nước dùng hầm xương 24h.',
        category: 'Main Course',
        price: 65000,
        imageUrl: 'https://cdn.tgdd.vn/2021/07/CookProduct/1200-1200x676-24.jpg',
        ingredients: ['Bánh phở', 'Thịt bò', 'Hành tây', 'Hành lá'],
        isVegetarian: false,
        isSpicy: false,
        preparationTime: 15,
        rating: 5.0,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Cơm Tấm Sườn Bì Chả',
        description: 'Cơm tấm Sài Gòn với sườn nướng than hoa.',
        category: 'Main Course',
        price: 55000,
        imageUrl: 'https://cdn.tgdd.vn/2021/04/CookProduct/1260-1200x676-22.jpg',
        ingredients: ['Gạo tấm', 'Sườn heo', 'Bì', 'Trứng', 'Chả trứng'],
        isVegetarian: false,
        isSpicy: false,
        preparationTime: 20,
        rating: 4.8,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Bún Bò Huế',
        description: 'Bún bò Huế cay nồng, đậm đà hương vị mắm ruốc.',
        category: 'Main Course',
        price: 60000,
        imageUrl: 'https://cdn.tgdd.vn/2020/07/CookProduct/1200-1200x676-85.jpg',
        ingredients: ['Bún to', 'Thịt bò', 'Giò heo', 'Mắm ruốc'],
        isVegetarian: false,
        isSpicy: true,
        preparationTime: 15,
        rating: 4.7,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Mì Ý Sốt Bò Bằm',
        description: 'Mì Spaghetti sốt cà chua bò bằm truyền thống.',
        category: 'Main Course',
        price: 70000,
        imageUrl: 'https://cdn.tgdd.vn/2020/07/CookProduct/1200-1200x676-78.jpg',
        ingredients: ['Mì Ý', 'Thịt bò băm', 'Cà chua', 'Hành tây'],
        isVegetarian: false,
        isSpicy: false,
        preparationTime: 20,
        rating: 4.5,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Cà Ri Gà',
        description: 'Cà ri gà nấu cốt dừa, ăn kèm bánh mì.',
        category: 'Main Course',
        price: 50000,
        imageUrl: 'https://cdn.tgdd.vn/2020/08/CookProduct/1200-1200x676-1.jpg',
        ingredients: ['Thịt gà', 'Khoai tây', 'Cà rốt', 'Nước cốt dừa'],
        isVegetarian: false,
        isSpicy: true,
        preparationTime: 30,
        rating: 4.6,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Cơm Chiên Dương Châu',
        description: 'Cơm chiên thập cẩm với tôm, trứng, đậu hà lan.',
        category: 'Main Course',
        price: 50000,
        imageUrl: 'https://cdn.tgdd.vn/2020/09/CookProduct/1200-1200x676-43.jpg',
        ingredients: ['Cơm', 'Trứng', 'Tôm', 'Đậu hà lan', 'Lạp xưởng'],
        isVegetarian: false,
        isSpicy: false,
        preparationTime: 15,
        rating: 4.4,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Đậu Hũ Tứ Xuyên',
        description: 'Đậu hũ non sốt cay tê phong cách Tứ Xuyên.',
        category: 'Main Course',
        price: 45000,
        imageUrl: 'https://cdn.tgdd.vn/2020/08/CookProduct/1200-1200x676-76.jpg',
        ingredients: ['Đậu hũ non', 'Thịt băm', 'Sa tế', 'Hành lá'],
        isVegetarian: false,
        isSpicy: true,
        preparationTime: 15,
        rating: 4.3,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Pizza Rau Củ',
        description: 'Pizza đế mỏng với các loại rau củ và phô mai.',
        category: 'Main Course',
        price: 120000,
        imageUrl: 'https://cdn.tgdd.vn/2020/09/CookProduct/1200-1200x676-65.jpg',
        ingredients: ['Bột mì', 'Phô mai', 'Ớt chuông', 'Nấm'],
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 30,
        rating: 4.7,
        createdAt: DateTime.now(),
      ),

      // --- DESSERT (Tráng miệng) ---
      MenuItemModel(
        itemId: '',
        name: 'Chè Khúc Bạch',
        description: 'Chè khúc bạch phô mai, hạnh nhân và vải.',
        category: 'Dessert',
        price: 30000,
        imageUrl: 'https://cdn.tgdd.vn/2020/07/CookProduct/1200-1200x676-66.jpg',
        ingredients: ['Gelatin', 'Sữa tươi', 'Hạnh nhân', 'Vải'],
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 10,
        rating: 4.8,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Bánh Flan',
        description: 'Bánh flan mềm mịn với sốt caramel và cà phê.',
        category: 'Dessert',
        price: 20000,
        imageUrl: 'https://cdn.tgdd.vn/2020/07/CookProduct/1200-1200x676-48.jpg',
        ingredients: ['Trứng gà', 'Sữa tươi', 'Đường'],
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 5,
        rating: 4.9,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Tiramisu',
        description: 'Bánh Tiramisu Ý thơm lừng vị cacao.',
        category: 'Dessert',
        price: 45000,
        imageUrl: 'https://cdn.tgdd.vn/2020/08/CookProduct/1200-1200x676-45.jpg',
        ingredients: ['Phô mai Mascarpone', 'Bánh ladyfinger', 'Cacao', 'Cà phê'],
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 10,
        rating: 4.7,
        createdAt: DateTime.now(),
      ),

      // --- BEVERAGE (Đồ uống) ---
      MenuItemModel(
        itemId: '',
        name: 'Trà Đào Cam Sả',
        description: 'Trà đào thanh mát kết hợp với cam và sả.',
        category: 'Beverage',
        price: 35000,
        imageUrl: 'https://cdn.tgdd.vn/2020/08/CookProduct/1200-1200x676-12.jpg',
        ingredients: ['Trà túi lọc', 'Đào ngâm', 'Cam', 'Sả'],
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 5,
        rating: 4.8,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Cà Phê Sữa Đá',
        description: 'Cà phê pha phin truyền thống với sữa đặc.',
        category: 'Beverage',
        price: 25000,
        imageUrl: 'https://cdn.tgdd.vn/2020/07/CookProduct/1200-1200x676-56.jpg',
        ingredients: ['Cà phê', 'Sữa đặc', 'Đá'],
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 5,
        rating: 4.9,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Nước Ép Dưa Hấu',
        description: 'Nước ép dưa hấu nguyên chất.',
        category: 'Beverage',
        price: 30000,
        imageUrl: 'https://cdn.tgdd.vn/2020/08/CookProduct/1200-1200x676-34.jpg',
        ingredients: ['Dưa hấu'],
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 5,
        rating: 4.5,
        createdAt: DateTime.now(),
      ),
      MenuItemModel(
        itemId: '',
        name: 'Sinh Tố Bơ',
        description: 'Sinh tố bơ béo ngậy.',
        category: 'Beverage',
        price: 40000,
        imageUrl: 'https://cdn.tgdd.vn/2020/07/CookProduct/1200-1200x676-11.jpg',
        ingredients: ['Bơ', 'Sữa đặc', 'Sữa tươi'],
        isVegetarian: true,
        isSpicy: false,
        preparationTime: 5,
        rating: 4.6,
        createdAt: DateTime.now(),
      ),
    ];

    WriteBatch batch = FirebaseFirestore.instance.batch();

    for (var item in dummyItems) {
      DocumentReference docRef = _menuCollection.doc(); // Tự động tạo ID
      item.itemId = docRef.id;
      batch.set(docRef, item.toMap());
    }

    await batch.commit();
    print("Đã thêm 20 món ăn mẫu thành công!");
  }
}