// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeDW4iV_RT83X27MVOfgg5aOlcBkKNSmQ',
    appId: '1:1088969302568:android:dbd5681aa6f73c4b034b1d',
    messagingSenderId: '1088969302568',
    projectId: 'exam-firebase-1771020152',
    storageBucket: 'exam-firebase-1771020152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1W5scmKjFR92DjyJQtU-FUX_3XRda_0Q',
    appId: '1:1088969302568:ios:767397a450991101034b1d',
    messagingSenderId: '1088969302568',
    projectId: 'exam-firebase-1771020152',
    storageBucket: 'exam-firebase-1771020152.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1771020152',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1W5scmKjFR92DjyJQtU-FUX_3XRda_0Q',
    appId: '1:1088969302568:ios:767397a450991101034b1d',
    messagingSenderId: '1088969302568',
    projectId: 'exam-firebase-1771020152',
    storageBucket: 'exam-firebase-1771020152.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp1771020152',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1N9ZqKrlphU9N8-w3NdRvE0zubaOGEbM',
    appId: '1:1088969302568:web:9ff063ccdd12942c034b1d',
    messagingSenderId: '1088969302568',
    projectId: 'exam-firebase-1771020152',
    authDomain: 'exam-firebase-1771020152.firebaseapp.com',
    storageBucket: 'exam-firebase-1771020152.firebasestorage.app',
    measurementId: 'G-DV5DX9P08P',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1N9ZqKrlphU9N8-w3NdRvE0zubaOGEbM',
    appId: '1:1088969302568:web:9ff063ccdd12942c034b1d',
    messagingSenderId: '1088969302568',
    projectId: 'exam-firebase-1771020152',
    authDomain: 'exam-firebase-1771020152.firebaseapp.com',
    storageBucket: 'exam-firebase-1771020152.firebasestorage.app',
    measurementId: 'G-DV5DX9P08P',
  );

}